package com.ducgao.spoyer_sdk.model
enum class Sport(val param: String) {
    Soccer("soccer"),
    Basketball("basketball"),
    Ice_Hockey("icehockey"),
    Tennis("tennis"),
    Badminton("badminton"),
    Volleyball("volleyball"),
    Table_Tennis("tabletennis"),
    Cricket("cricket"),
    Rugby_Union("rugbyunion"),
    American_Football("football"),
    Snooker("snooker"),
    Darts("darts"),
    Baseball("baseball"),
    Rugby_League("rugbyleague"),
    Australian_Rules("australianrules"),
    Bowls("bowls"),
    Gaelic_Sports("gaelicfootball"),
    Handball("handball"),
    Futsal("futsal"),
    Floorball("floorball"),
    Beach_Volleyball("beachvolleyball"),
    Water_Polo("waterpolo"),
    Squash("squash"),
    E_sport("esport"),
    Boxing_UFC("boxing")
}